# Loop through the imagePullSecrets to create image pull secrets
{{- range .Values.imagePullSecrets }}
{{- if and .name .create }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .name | quote }}
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .url (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
