{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "pontoon.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $ingressName := default ( include "pontoon.fullname" . ) .Values.ingress.name -}}
{{- if and (.Capabilities.APIVersions.Has "networking.k8s.io/v1") (semverCompare ">= 1.19.x" .Capabilities.KubeVersion.Version) -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    app: {{ include "pontoon.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.ingress.labels }}
{{ .Values.ingress.labels | toYaml | trimSuffix "\n"| indent 4 -}}
{{- end}}
{{- if .Values.ingress.annotations }}
  annotations:
{{ .Values.ingress.annotations | toYaml | trimSuffix "\n" | indent 4 -}}
{{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
{{- if .Values.ingress.hosts }}
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
        - path: {{ $.Values.ingress.routerPath }}
          {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          pathType: {{ $.Values.ingress.pathType }}
          backend:
            service:
              name: {{ $serviceName }}
              port: 
                number: {{ $servicePort }}
          {{- else }}
          backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
          {{- end }}
  {{- end -}}
{{- end -}}
{{- end -}}
