---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-control-plane-traffic
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          linkerd.io/control-plane-ns: linkerd
    ports:
    - port: 4143
      protocol: TCP
    - port: 4191
      protocol: TCP
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          linkerd.io/control-plane-ns: linkerd
  policyTypes:
  - Ingress
  - Egress
---
# Allow for incoming public traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-internet-ingress
spec:
  podSelector:
    matchLabels:
      networking/allow-internet-ingress: "true"
  ingress:
    - from: []
  policyTypes:
    - Ingress
---
# Allow for outgoing traffic to external services
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-internet-egress
spec:
  podSelector:
    matchLabels:
      networking/allow-internet-egress: "true"
  egress:
    - {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-network-policy
spec:
  podSelector:
    matchLabels:
      app: redis
      release: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: redis
          release: {{ .Release.Name }}
    ports:
    - port: 4143
      protocol: TCP
    - port: 6379
      protocol: TCP
    - port: 26379
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          networking/allow-redis-access: "true"
    ports:
    - port: 4143
      protocol: TCP
    - port: 6379
      protocol: TCP
    - port: 26379
      protocol: TCP
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
          release: {{ .Release.Name }}
    ports:
    - port: 4143
      protocol: TCP
    - port: 6379
      protocol: TCP
    - port: 26379
      protocol: TCP
  policyTypes:
  - Ingress
  - Egress
