kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "pontoon.fullname" . }}-secrets"
type: Opaque
data:
  SECRET_KEY: {{ .Values.secretKey | b64enc | quote }}
  {{- if not .Values.postgres.enabled }}
  DATABASE_URL: {{ .Values.postgres.databaseUrl | b64enc | quote }}
  {{- end }}
