apiVersion: v1
kind: Service
metadata:
  name: {{ include "pontoon.fullname" . }}
  labels:
    {{- include "pontoon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "pontoon.fullname" . }}
    component: "pontoon"
