# SSH Keys and config are used to authenticate with VCS servers via SSH
# Learn more at
{{- if or .Values.ssh.config .Values.ssh.privateKeys }}
kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "pontoon.fullname" . }}-ssh-secrets"
type: Opaque
data:
  {{- if .Values.ssh.config }}
  config: {{ .Values.ssh.config }}
  {{- end }}
  {{- if .Values.ssh.privateKeys }}
  {{ .Values.ssh.privateKeys | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
