apiVersion: v2
name: pontoon
home: https://github.com/mozilla/pontoon
version: 1.0.0
# Pontoon no longer cuts releases.
# See https://github.com/mozilla/pontoon/releases/tag/2018-12-19
appVersion: latest
type: application
description: A Helm chart for Pontoon, a Mozilla's Localization Platform.
keywords:
  - i18n
  - pontoon
sources:
  - https://github.com/mozilla/pontoon
icon: https://pontoon.mozilla.org/static/img/logo.svg
