apiVersion: v2
name: pontoon
home: https://github.com/mozilla/pontoon
version: 2.0.0
# Pontoon no longer cuts releases.
# See https://github.com/mozilla/pontoon/releases/tag/2018-12-19
# and https://hub.docker.com/r/skillsnetwork/pontoon/tags
appVersion: db4dd60
type: application
description: A Helm chart for Pontoon, a Mozilla's Localization Platform.
keywords:
  - i18n
  - pontoon
sources:
  - https://github.com/mozilla/pontoon
  - https://github.com/ibm-skills-network/charts
icon: https://pontoon.mozilla.org/static/img/logo.svg
dependencies:
  - name: postgresql
    version: 11.6.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled
    alias: postgres
  - name: rabbitmq
    version: 10.1.8
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
