# Default values for pontoon.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

siteUrl: ""
secretKey: "supersecretkeychangeme" # change me
pontoonHome: "/app"

forceSsl: true

gunicornArgs:
  - "pontoon.wsgi:application"
  - "--bind=0.0.0.0"

# Recommended production settings
defaultEnvVars:
  - name: CELERY_ALWAYS_EAGER
    value: "False"
  - name: DJANGO_DEBUG
    value: "False"
  - name: DJANGO_DEV
    value: "False"
extraEnvVars: []

# NOTE: This should be a multiline value
# A valid Python script that mounts at pontoon/settings/custom.py
# Which can be used to override the default Django settings pontoon/settings/base.py
# https://github.com/mozilla/pontoon/blob/master/pontoon/settings/base.py
extraSettingsModule: ""
##  from .base import *
##  BROKER_LOGIN_METHOD = "PLAIN"
##  DATABASES["default"]["OPTIONS"]["sslmode"] = "allow"

ssh:
  # privateKeys is a dictionary of private key name and base64-encoded string
  # config is e base64-encoded string
  #
  ## How to get base64-encoded string?
  ## echo "~/.ssh/id_rsa" | base64 | pbcopy
  ## echo "~/.ssh/config" | base64 | pbcopy
  ##
  ## Example:
  ## privateKeys:
  ##   id_rsa_1: <some_base64_encoded_ssh_private_key>
  ##   id_rsa_2: <some_base64_encoded_ssh_private_key
  ## config: <base64_encoded_ssh_config>
  privateKeys: {}
  config: ""
  mountPath: "/home/pontoon/.ssh"

replicaCount: 1
image:
  repository: skillsnetwork/pontoon
  pullPolicy: IfNotPresent
  # Look for the latest tag at https://hub.docker.com/repository/docker/skillsnetwork/pontoon
  tag: "db4dd60"

worker:
  enabled: true
  replicaCount: 1
  celeryArgs:
    - "worker"
    - "--app=pontoon.base.celeryapp"
    - "--loglevel=info"
    - "--without-gossip"
    - "--without-mingle"
    - "--without-heartbeat"
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

# Schedule job to sync projects with external VCS
# https://mozilla-pontoon.readthedocs.io/en/latest/admin/deployment.html#scheduled-jobs
syncProjectCronjob:
  schedule: "@every 30m"
  suspend: false
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  securityContext: {}
  extraVolumeMounts: []
  extraVolumes: []
  # Add init containers to pod
  initContainers: {}
  ## Command and args for running the container
  command: []
  args: []

# Migration job to perform database migration
migrationJob:
  extraVolumeMounts: []
  extraVolumes: []
  # Add init containers to pod
  initContainers: { }
  ## Command and args for running the container
  command: []
  args: []

# Configuration values for the postgres dependency
# ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/README.md
#
postgres:
  enabled: false
  postgresqlUsername: "postgres"
  postgresqlDatabase: "pontoon"
  # If NOT using the PostgreSQL in this chart (postgres.enabled=false), 
  # you must specify a custom databasUrl here or pontoon won't work
  databaseUrl: ""

# Configuration values for the rabbitmq dependency
# ref: https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/README.md
#
rabbitmq:
  enabled: false
  auth:
    username: "pontoon"
  url: ""

imagePullSecrets: []
# A list of imagePullSecrets
# `create` indicates whether it is an existing secrets
# or a new secret should be created
#  - name: dockerhub
#    create: true
#    url: ""https://index.docker.io/v1/"
#    username: "username"
#    password: "password"
#  - name: more
#    create: false

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  servicename:
  type: ClusterIP
  port: 8000
  externalPort: 8000

ingress:
  enabled: false
  routerPath: "/"
  pathType: "ImplementationSpecific"
  labels: {}
  annotations: {}
    # Ingress annotations
    # external-dns.alpha.kubernetes.io/hostname: "pontoon.example.com"
    # external-dns.alpha.kubernetes.io/target: "ingress.hostname"
    # cert-manager.io/cluster-issuer: acme-issuer
    # acme.cert-manager.io/http01-edit-in-place: "true"
  hosts: []
    # - "pontoon.example.com"
  tls: []
  # - hosts:
  #   - "pontoon.example.com"
  #   secretName: "tls-cert-secret"


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
